---
kind: pipeline
type: docker
name: build-s390x

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
  - name: build
    image: rancher/dapper:v0.5.8
    failure: ignore
    commands:
      - dapper -f Dockerfile --target dapper make dapper-ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
      ref:
        - refs/head/master
        - refs/tags/*

  - name: publish-dist-artifacts
    image: rancher/drone-images:github-release-s390x
    failure: ignore
    settings:
      api_key:
        from_secret: github_token
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-s390x.txt
      checksum_flatten: true
      files:
        - dist/artifacts/*
      prerelease: true
    when:
      event:
        - tag
      ref:
        - refs/head/master
        - refs/tags/*
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
...
